// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUnUd4ia-nzqY7Z0-3_vsl6OwHd_E7u1A',
    appId: '1:577845830533:web:1c190ec5724b692a155aec',
    messagingSenderId: '577845830533',
    projectId: 'gatex-79c53',
    authDomain: 'gatex-79c53.firebaseapp.com',
    storageBucket: 'gatex-79c53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-nW8kz-6iRCkOPZHktO_Kg-7cBxLHpM',
    appId: '1:577845830533:android:08435e84e89bca79155aec',
    messagingSenderId: '577845830533',
    projectId: 'gatex-79c53',
    storageBucket: 'gatex-79c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4cRw1EXwmk9FOiNO_g4xS9UgbuPBtkc',
    appId: '1:577845830533:ios:987e4983f4e960b1155aec',
    messagingSenderId: '577845830533',
    projectId: 'gatex-79c53',
    storageBucket: 'gatex-79c53.firebasestorage.app',
    iosBundleId: 'com.example.secureGatex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4cRw1EXwmk9FOiNO_g4xS9UgbuPBtkc',
    appId: '1:577845830533:ios:987e4983f4e960b1155aec',
    messagingSenderId: '577845830533',
    projectId: 'gatex-79c53',
    storageBucket: 'gatex-79c53.firebasestorage.app',
    iosBundleId: 'com.example.secureGatex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUnUd4ia-nzqY7Z0-3_vsl6OwHd_E7u1A',
    appId: '1:577845830533:web:3c0b7bf823076021155aec',
    messagingSenderId: '577845830533',
    projectId: 'gatex-79c53',
    authDomain: 'gatex-79c53.firebaseapp.com',
    storageBucket: 'gatex-79c53.firebasestorage.app',
  );
}
